/*Dirlist File Initializer*/

#include <stdio.h>
#include <time.h>
#include "dirlist.h"

FILE *file;

FILE *file_init(char *path, DIR_OPTIONS *options) {
	FILE *file_recurse;
	
	if(options->output) {
		file=fopen(path, "w");
		print_file(file);
		return file;
	}
	else if(options->filetype) {
		file_recurse=fopen(path, "w");
		print_file(file_recurse);
		return file_recurse;
	}
	else {
		file=fopen("./dirlist.txt", "w");
		print_file(file);
		return file;
	}
}

void print_file(FILE *file) {
	fprintf(file,
		"; Generated by Dirlist - an extremely fast directory lister.\n"
		"%s",get_date()
	);
}

char *get_date(void) {
	int month;
	int day;
	int year;
	char *wdays[] = {
		"Sunday",
		"Monday",
		"Tuesday",
		"Wednesday",
		"Thursday",
		"Friday",
		"Saturday"
	};
	struct tm *t;
	time_t now;
	static char output[256]; // function returns address of local variable
	
	time(&now); // store the current (epoch) time to now
	t = localtime(&now); // load the tm structure
	
	month = t->tm_mon; // interchange the variables
	day = t->tm_mday;
	year = t->tm_year;
	
	sprintf(output,
		"; Generated %s, %d/%d/%d, at %d:%02d:%02d %s\n;\n", // with comment semicolons, may be a use in the future
		wdays[t->tm_wday],
		month +1, day, year + 1900,
		t->tm_hour > 12 ? t->tm_hour - 12 : t->tm_hour,
		t->tm_min,
		t->tm_sec,
		t->tm_hour > 12 ? "PM" : "AM"
	);
	return output;
}
