/**********************************************************
      Prime Numbers: fprint.c. Copyright © 2008 by samus250

This program generates prime numbers using a simple algorithm
and prints the result to a text file in the same directory the 
program was opened.

This program is distributed in the hopes that it will be useful and
 comes with ABSOLUTELY NO WARRANTY.

************************************************************/

#include <stdio.h>
#include "primes.h"

FILE *primefile;
extern u_long_64 prime_numbers,first_range,second_range;

void file_init(void)
{
	/*Create Text File!*/
	primefile=fopen("./primes.txt","w");
	fprintf(primefile,"***** File Generated by Prime Numbers " VERSION", ©2008 samus250. All Rights Reserved *****\n");
	get_date(primefile);
}

void results(void)
{
	printf("\n\nI found " VAL_FORMAT " prime numbers from " VAL_FORMAT " to " VAL_FORMAT "!!!\n",prime_numbers,first_range,second_range);
	printf("-------------------------------------------------------------------------------");
	fprintf(primefile,"\n\nI found " VAL_FORMAT " prime numbers from " VAL_FORMAT " to " VAL_FORMAT "!!!\n",prime_numbers,first_range,second_range);
	fclose(primefile);
}
