/*****************************************************************

SemiPrime Numbers: fprint.c. Copyright © 2008 by samus250

This program generates prime numbers using a simple algorithm
and prints the result to a text file in the same directory the 
program was opened.

This program is distributed in the hopes that it will be useful 
and comes with ABSOLUTELY NO WARRANTY.

******************************************************************/

#include <stdio.h>
#include "primes.h"

FILE *file_init(FILE *primefile)
{
	primefile=fopen("./semiprimes.txt","w");
	fprintf(primefile,"***** File Generated by Prime Numbers " VERSION", ©2008 samus250. All Rights Reserved *****\n");
	get_date(primefile);
	return primefile;
}

void results(FILE *primefile, u_long_64 first_range, u_long_64 second_range, u_long_64 semiprimes_count)
{
	printf(
		"\n\nI found " VAL_FORMAT " semiprime numbers from " VAL_FORMAT " to " VAL_FORMAT "!!!\n"
		"-------------------------------------------------------------------------------"
		, semiprimes_count, first_range, second_range
	);
	fprintf(primefile,
		"\n\nI found " VAL_FORMAT " semiprime numbers from " VAL_FORMAT " to " VAL_FORMAT "!!!\n",
		semiprimes_count, first_range, second_range
	);
	
	fclose(primefile);
}

